[project]
name = "memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.10",
    "langchain-openai>=0.2.5",
    "langgraph>=0.2.34",
    "pydantic>=2.8.0",
    "python-dotenv>=1.0.1",
]
